=== nbacquey/dtop-implement/XML/Trees/tree.dtd
<!ELEMENT tree (signature,node)>

<!ELEMENT signature (symbol+) >

<!ELEMENT symbol EMPTY >

<!ATTLIST symbol 
  name      CDATA   #REQUIRED
  arity     CDATA   #REQUIRED >
  
<!ELEMENT node (node*)>

<!ATTLIST node
  symbol    CDATA #REQUIRED >

=== nbacquey/dtop-implement/XML/Trees/tree_DI_2.xml
<?xml version="1.0" encoding="utf-8"?>
<!DOCTYPE tree SYSTEM "tree.dtd">
<tree>
  <signature>
    <symbol name="f" arity="2"/>
    <symbol name="u" arity="1"/>
    <symbol name="a" arity="0"/>
    <symbol name="b" arity="0"/>
  </signature>

  
  <node symbol= "u">
    <node symbol = "u">
      <node symbol = "u">
        <node symbol = "b"/>    
      </node>
    </node>
  </node>
  
</tree>

=== nbacquey/dtop-implement/XML/Trees/tree_1_by_transducer_1.xml
<?xml version="1.0" encoding="utf-8"?>
<!DOCTYPE tree SYSTEM "tree.dtd">
<tree>
   <signature>
      <symbol name="g" arity="2"/>
      <symbol name="a" arity="1"/>
      <symbol name="b" arity="1"/>
      <symbol name="c" arity="1"/>
      <symbol name="#" arity="0"/>
   </signature>
   <node symbol="g">
      <node symbol="c">
         <node symbol="b">
            <node symbol="g">
               <node symbol="c">
                  <node symbol="a">
                     <node symbol="#"/>
                  </node>
               </node>
               <node symbol="c">
                  <node symbol="#"/>
               </node>
            </node>
         </node>
      </node>
   </node>
</tree>

=== nbacquey/dtop-implement/XML/Trees/tree_2.xml
<?xml version="1.0" encoding="utf-8"?>
<!DOCTYPE tree SYSTEM "tree.dtd">
<tree>
  <signature>
    <symbol name="f" arity="2"/>
    <symbol name="a" arity="1"/>
    <symbol name="b" arity="1"/>
    <symbol name="#" arity="0"/>
  </signature>

  <node symbol="f">
    <node symbol = "a">
      <node symbol = "b">
	<node symbol = "a">
          <node symbol = "a">
            <node symbol = "#"/>
          </node>
	</node>
      </node>
    </node>
    <node symbol = "b">
      <node symbol = "a">
        <node symbol = "b">
          <node symbol = "a">
            <node symbol = "b">
              <node symbol = "a">
                <node symbol = "#"/>
              </node>
            </node>
          </node>
        </node>
      </node>
    </node>
  </node>
  
</tree>

=== nbacquey/dtop-implement/XML/Trees/tree_2_by_transducer_2.xml
<?xml version="1.0" encoding="utf-8"?>
<!DOCTYPE tree SYSTEM "tree.dtd">
<tree>
   <signature>
      <symbol name="a" arity="1"/>
      <symbol name="b" arity="1"/>
      <symbol name="#" arity="0"/>
   </signature>
   <node symbol="a">
      <node symbol="b">
         <node symbol="a">
            <node symbol="a">
               <node symbol="#"/>
            </node>
         </node>
      </node>
   </node>
</tree>
