=== nbacquey/dtop-implement/XML/Transducers/transducer.dtd
<!ELEMENT transducer (signature-in,signature-out,states,axiom,rules) >

<!ELEMENT signature-in (symbol+) >

<!ELEMENT signature-out (symbol+) >

<!ELEMENT symbol EMPTY >

<!ELEMENT states (state+) >

<!ELEMENT state EMPTY>

<!ELEMENT axiom (context | call) >

<!ELEMENT context ((call | context)*) >

<!ELEMENT call EMPTY >

<!ELEMENT rules (rule)* >

<!ELEMENT rule (context | call) >

<!ATTLIST symbol 
  name      CDATA   #REQUIRED
  arity     CDATA   #REQUIRED >

<!ATTLIST state
  name      CDATA   #REQUIRED >
  
<!ATTLIST context
  symbol    CDATA   #REQUIRED >

<!ATTLIST call
  state     CDATA   #REQUIRED
  variable  CDATA   #REQUIRED >
  
<!ATTLIST rule
  symbol    CDATA   #REQUIRED
  state     CDATA   #REQUIRED >

=== nbacquey/dtop-implement/XML/Transducers/transducer_DI4.xml
<?xml version="1.0" encoding="utf-8"?>
<!DOCTYPE transducer SYSTEM "transducer.dtd">
<transducer>
  
  <signature-in>
    <symbol name="g" arity="2"/>
    <symbol name="a" arity="0"/>
    <symbol name="b" arity="0"/>    
  </signature-in>
  
  <signature-out>
    <symbol name="g" arity="2"/>
    <symbol name="a" arity="0"/>
    <symbol name="b" arity="0"/>   
  </signature-out>
  
  
  <states> 
    <state name="1"/>
    <state name="2"/>
  </states>
  
  <axiom>
    <call state="1" variable="1"/>
  </axiom>
  
  <rules>
    
    <rule state="1" symbol="g">
      <call state="2" variable="2" />
    </rule>
    
    <rule state="2" symbol="a">
      <context symbol="a"/>
    </rule>
    
    <rule state="2" symbol="b">
      <context symbol="b"/>
    </rule>
    
    <rule state="2" symbol="g">
      <context symbol="g">
        <call state="2" variable="1" />
        <call state="2" variable="2" />
      </context>
    </rule>
    
  </rules>
  
</transducer>

=== nbacquey/dtop-implement/XML/Transducers/transducer_1.xml
<?xml version="1.0" encoding="utf-8"?>
<!DOCTYPE transducer SYSTEM "transducer.dtd">
<transducer>
  
  <signature-in>
    <symbol name="f" arity="2"/>
    <symbol name="a" arity="1"/>
    <symbol name="b" arity="1"/>
    <symbol name="#" arity="0"/>    
  </signature-in>
  
  <signature-out>
    <symbol name="g" arity="2"/>
    <symbol name="a" arity="1"/>
    <symbol name="b" arity="1"/>
    <symbol name="c" arity="1"/>
    <symbol name="#" arity="0"/>  
  </signature-out>
  
  
  <states> 
    <state name="1"/>
    <state name="2"/>
  </states>
  
  <axiom>
    <call state="1" variable="1"/>
  </axiom>
  
  <rules>
    <rule state="1" symbol="f">
      <context symbol="g">
        <call state="1" variable="2" />
        <call state="2" variable="1" />
      </context>
    </rule>
    
    <rule state="2" symbol="f">
      <context symbol="g">
        <call state="1" variable="2" />
        <call state="2" variable="1" />
      </context>
    </rule>
    
    <rule state="1" symbol="a">
      <context symbol="a">
        <call state="1" variable="1"/>
      </context>
    </rule>
    
    <rule state="1" symbol="b">
      <context symbol="c">
        <call state="1" variable="1"/>
      </context>
    </rule>
    
    <rule state="1" symbol="#">
      <context symbol="#"/>
    </rule>
    
    <rule state="2" symbol="a">
      <context symbol="c">
        <call state="2" variable="1"/>
      </context>
    </rule>
    
    <rule state="2" symbol="b">
      <context symbol="b">
        <call state="2" variable="1"/>
      </context>
    </rule>
    
    <rule state="2" symbol="#">
      <context symbol="#"/>
    </rule>
  </rules>
  
</transducer>

=== nbacquey/dtop-implement/XML/Transducers/transducer_2.xml
<?xml version="1.0" encoding="utf-8"?>
<!DOCTYPE transducer SYSTEM "transducer.dtd">
<transducer>
  
  <signature-in>
    <symbol name="f" arity="2"/>
    <symbol name="a" arity="1"/>
    <symbol name="b" arity="1"/>
    <symbol name="#" arity="0"/>    
  </signature-in>
  
  <signature-out>
    <symbol name="a" arity="1"/>
    <symbol name="b" arity="1"/>
    <symbol name="#" arity="0"/>  
  </signature-out>
  
  
  <states> 
    <state name="0"/>
  </states>
  
  <axiom>
    <call state="0" variable="1"/>
  </axiom>
  
  <rules>
    <rule state="0" symbol="f">
      <call state="0" variable="1" />
    </rule>
    
    <rule state="0" symbol="a">
      <context symbol="a">
        <call state="0" variable="1"/>
      </context>
    </rule>
    
    <rule state="0" symbol="b">
      <context symbol="b">
        <call state="0" variable="1"/>
      </context>
    </rule>
    
    <rule state="0" symbol="#">
      <context symbol="#"/>
    </rule>
  </rules>
  
</transducer>

=== nbacquey/dtop-implement/XML/Transducers/trans_des_1.xml
<?xml version="1.0" encoding="utf-8"?>
<!DOCTYPE transducer SYSTEM "transducer.dtd">
<transducer>
  
  <signature-in>
    <symbol name="f" arity="2"/>
    <symbol name="g" arity="2"/>
    <symbol name="#" arity="0"/>
    <symbol name="pkg" arity="0"/>
  </signature-in>
  
  <signature-out>
    <symbol name="f" arity="2"/>
    <symbol name="g" arity="2"/>
    <symbol name="#" arity="0"/>    
  </signature-out>  
  
  <states> 
    <state name="1"/>
    <state name="2"/>
  </states>
  
  <axiom>
    <call state="1" variable="1"/>
  </axiom>
  
  <rules>
    
    <rule state="1" symbol="f">
      <context symbol="f">
        <call state="1" variable="1" />
        <call state="2" variable="2" />
      </context>
    </rule>
    
    <rule state="2" symbol="f">
      <context symbol="f">
        <call state="2" variable="1" />
        <call state="2" variable="2" />
      </context>
    </rule>
    
    <rule state="1" symbol="g">
      <context symbol="g">
        <call state="1" variable="1" />
        <call state="2" variable="2" />
      </context>
    </rule>
    
    <rule state="2" symbol="g">
      <context symbol="g">
        <call state="2" variable="1" />
        <call state="2" variable="2" />
      </context>
    </rule>
    
    <rule state="1" symbol="#">
      <context symbol="#"/>
    </rule>
    
    <rule state="1" symbol="pkg">
      <context symbol="#"/>
    </rule>
    
    <rule state="2" symbol="#">
      <context symbol="#"/>
    </rule>
    
  </rules>
  
</transducer>

=== nbacquey/dtop-implement/XML/Transducers/transducer_DI2.xml
<?xml version="1.0" encoding="utf-8"?>
<!DOCTYPE transducer SYSTEM "transducer.dtd">
<transducer>
  
  <signature-in>
    <symbol name="f" arity="2"/>
    <symbol name="u" arity="1"/>
    <symbol name="a" arity="0"/>
    <symbol name="b" arity="0"/>    
  </signature-in>
  
  <signature-out>
    <symbol name="a" arity="0"/>
    <symbol name="b" arity="0"/>   
  </signature-out>
  
  
  <states> 
    <state name="1"/>
  </states>
  
  <axiom>
    <call state="1" variable="1"/>
  </axiom>
  
  <rules>
    
    <rule state="1" symbol="u">
      <call state="1" variable="1" />
    </rule>
    
    <rule state="1" symbol="a">
      <context symbol="a"/>
    </rule>
    
    <rule state="1" symbol="b">
      <context symbol="b"/>
    </rule>
    
    <rule state="1" symbol="f">
      <call state="1" variable="1"/>
    </rule>
    
  </rules>
  
</transducer>

=== nbacquey/dtop-implement/XML/Transducers/transducer_DI1.xml
<?xml version="1.0" encoding="utf-8"?>
<!DOCTYPE transducer SYSTEM "transducer.dtd">
<transducer>
  
  <signature-in>
    <symbol name="f" arity="2"/>
    <symbol name="u" arity="1"/>
    <symbol name="a" arity="0"/>
    <symbol name="b" arity="0"/>    
  </signature-in>
  
  <signature-out>
    <symbol name="g" arity="3"/>
    <symbol name="f" arity="2"/>
    <symbol name="u" arity="1"/>
    <symbol name="a" arity="0"/>
    <symbol name="b" arity="0"/>   
  </signature-out>
  
  
  <states> 
    <state name="1"/>
    <state name="2"/>
    <state name="3"/>
    <state name="4"/>
  </states>
  
  <axiom>
    <context symbol = "g">
      <call state="1" variable="1"/>
      <call state="2" variable="1"/>
      <call state="3" variable="1"/>
    </context>
  </axiom>
  
  <rules>
    
    <rule state="1" symbol="u">
      <context symbol="u">
        <call state="1" variable="1" />
      </context>
    </rule>
    
    <rule state="1" symbol="a">
      <context symbol="a"/>
    </rule>
    
    <rule state="1" symbol="b">
      <context symbol="b"/>
    </rule>
    
    <rule state="2" symbol="f">
      <context symbol="f">
        <call state="4" variable="1"/>
        <call state="4" variable="2"/>
      </context>
    </rule>
    
    <rule state="4" symbol="f">
      <context symbol="f">
        <call state="2" variable="1"/>
        <call state="2" variable="2"/>
      </context>
    </rule>
    
    <rule state="2" symbol="u">
      <context symbol="u">
        <call state="4" variable="1"/>
      </context>
    </rule>
    
    <rule state="4" symbol="u">
      <context symbol="u">
        <call state="2" variable="1"/>
      </context>
    </rule>
    
    <rule state="4" symbol="b">
      <context symbol="b"/>
    </rule>
    
    <rule state="4" symbol="a">
      <context symbol="a"/>
    </rule>
    
    <rule state="3" symbol="f">
      <context symbol="f">
        <call state="3" variable="1"/>
        <call state="3" variable="2"/>
      </context>
    </rule>
    
    <rule state="3" symbol="u">
      <context symbol="u">
        <call state="3" variable="1"/>
      </context>
    </rule>
    
    <rule state="3" symbol="b">
      <context symbol="b"/>
    </rule>
    
  </rules>
  
</transducer>
